name: Daily Database Build
on:
  schedule:
    - cron: "30 22 * * *" # Every day at 7:30am KST
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SEGA_ID: ${{ secrets.SEGA_ID }}
      SEGA_PASSWORD: ${{ secrets.SEGA_PASSWORD }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: main
      - name: Install dependencies
        run: yarn
      - name: Build record database
        run: yarn generate:records
      - name: Build song database
        run: yarn generate:music-db
      - name: Build meta database
        run: yarn generate:meta-db
      - name: Build internal level database
        run: yarn generate:internal-db
      - name: Build stamp card
        run: yarn generate:stamp
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
  build:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: main
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/maimai'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          
